spring:
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:school-app-cucumber-db
      username: sa
      password:
        driverClassName: org.h2.Driver